# Generated by Django 5.1 on 2024-08-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_producer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='api.producer'),
        ),
    ]
